version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
